# Generated by Django 2.0 on 2020-12-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='client_first_discout',
            new_name='maximum_discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='client_last_discount',
            new_name='minimum_discount',
        ),
    ]
