# Generated by Django 2.0 on 2020-12-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201220_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maximum_discount',
            new_name='lowest_price_offer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='minimum_discount',
            new_name='maximum_price_offer',
        ),
    ]
